syntax = "proto3";

option java_multiple_files = true;
option java_package = "es.um.sisdist.backend.grpc";

package es.um.sisdist.backend.grpc;

// El mensaje que envía el usuario
message ChatRequest {
    string user_id = 1;   // Para identificar y autenticar al usuario 
    string dialogue_id = 2;   // Para mantener el hilo de la conversación
    string prompt = 3;       // El texto que escribe el usuario
}

// El mensaje que responde el servidor
message ChatResponse {
	string dialogue_id = 1; 	// Confirmación de la sesión
    string answer = 2;			// Respuesta generada al prompt
    long timestamp = 3;   		// Marca de tiempo para ordenar la conversación
}

// Definición del servicio
service LLMService {
    // Procesa un prompt y devuelve la respuesta completa
    rpc processPrompt (ChatRequest) returns (ChatResponse);
}

