syntax = "proto3";

option java_package = "es.um.sisdist.backend.grpc";
option java_multiple_files = true;

package llmchat;

// El mensaje que envía el cliente
message ChatRequest {
    string user_token = 1;   // Para identificar y autenticar al usuario 
    string session_id = 2;   // Para mantener el hilo de la conversación
    string prompt = 3;       // El texto que escribe el usuario
}

// El mensaje que responde el servidor
message ChatResponse {
    string response_text = 1;
    int32 tokens_used = 2;   // Ejemplo de metadato de respuesta
}

// Definición del servicio
service LLMService {
    // El servidor enviará múltiples ChatResponse para una sola ChatRequest
    rpc GetChatStream (ChatRequest) returns (stream ChatResponse);
}
