services:

  ssdd-frontend:
    build: ./frontend
    image: dsevilla/ssdd-frontend:1.0
    ports:
      - 5010:5010
    env_file: sql.env
    environment:
      - FLASK_APP=app/app.py
      - FLASK_DEBUG=true
      - DEBUG_METRICS=true
      - PORT=5010
    depends_on:
      db-mysql:
        condition: service_healthy

  ssdd-llamachat:
    image: dsevilla/ssdd-llamachat:1.0
    ports:
      - 5020:5020

  db-mysql:
    build: db-mysql/.
    ports:
      - 3306
    env_file: sql.env
    healthcheck:
      test: echo 'SELECT 1' | mysql -h db-mysql -u root -p$$MYSQL_ROOT_PASSWORD $$MYSQL_DATABASE
      interval: 10s
      timeout: 10s
      retries: 7
      start_period: 20s

  backend-rest:
    build: ./backend-rest/es.um.sisdist.backend.Service
    image: dsevilla/ssdd-backend-rest:1.0
    ports:
      - 8080:8080
    env_file: sql.env
    environment:
      - GRPC_SERVER=backend-grpc
    depends_on:
      db-mysql:
        condition: service_healthy
   

  backend-grpc:
    build: ./backend-grpc/es.um.sisdist.backend.grpc.GrpcServiceImpl
    image: dsevilla/ssdd-backend-grpc:1.0
    ports:
      - 50051
    env_file: sql.env
    environment:
      - LLAMACHAT_HOST=ssdd-llamachat
      - LLAMACHAT_PORT=5020
      - JAVA_TOOL_OPTIONS=-Djdk.httpclient.allowRestrictedHeaders=expect,connection
    depends_on:
      db-mysql:
        condition: service_healthy

  prometheus: 
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes: 
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - ssdd-frontend
      - backend-rest
